version: "3"

services:
  web:
    container_name: web
    image: nginx:1.17.8-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./dest:/var/www/html
